package dot.curse.matule.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF00658B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF48B2E7)
val onPrimaryContainerLight = Color(0xFF00425C)
val secondaryLight = Color(0xFF006389)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF2C7CA4)
val onSecondaryContainerLight = Color(0xFFFCFCFF)
val tertiaryLight = Color(0xFF005675)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF2B6E8F)
val onTertiaryContainerLight = Color(0xFFCEEBFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF6FAFE)
val onBackgroundLight = Color(0xFF181C1F)
val surfaceLight = Color(0xFFF6FAFE)
val onSurfaceLight = Color(0xFF181C1F)
val surfaceVariantLight = Color(0xFFDAE4EC)
val onSurfaceVariantLight = Color(0xFF3E484F)
val outlineLight = Color(0xFF6F7880)
val outlineVariantLight = Color(0xFFBEC8D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3134)
val inverseOnSurfaceLight = Color(0xFFEDF1F6)
val inversePrimaryLight = Color(0xFF7ED0FF)
val surfaceDimLight = Color(0xFFD7DADF)
val surfaceBrightLight = Color(0xFFF6FAFE)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F4F8)
val surfaceContainerLight = Color(0xFFEAEEF3)
val surfaceContainerHighLight = Color(0xFFE5E8ED)
val surfaceContainerHighestLight = Color(0xFFDFE3E7)

val primaryDark = Color(0xFF7ED0FF)
val onPrimaryDark = Color(0xFF00344A)
val primaryContainerDark = Color(0xFF48B2E7)
val onPrimaryContainerDark = Color(0xFF00425C)
val secondaryDark = Color(0xFF87CFFB)
val onSecondaryDark = Color(0xFF00344B)
val secondaryContainerDark = Color(0xFF4E98C2)
val onSecondaryContainerDark = Color(0xFF002D41)
val tertiaryDark = Color(0xFF91CEF3)
val onTertiaryDark = Color(0xFF00344A)
val tertiaryContainerDark = Color(0xFF2B6E8F)
val onTertiaryContainerDark = Color(0xFFCEEBFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1417)
val onBackgroundDark = Color(0xFFDFE3E7)
val surfaceDark = Color(0xFF0F1417)
val onSurfaceDark = Color(0xFFDFE3E7)
val surfaceVariantDark = Color(0xFF3E484F)
val onSurfaceVariantDark = Color(0xFFBEC8D0)
val outlineDark = Color(0xFF88929A)
val outlineVariantDark = Color(0xFF3E484F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDFE3E7)
val inverseOnSurfaceDark = Color(0xFF2C3134)
val inversePrimaryDark = Color(0xFF00658B)
val surfaceDimDark = Color(0xFF0F1417)
val surfaceBrightDark = Color(0xFF353A3D)
val surfaceContainerLowestDark = Color(0xFF0A0F12)
val surfaceContainerLowDark = Color(0xFF181C1F)
val surfaceContainerDark = Color(0xFF1C2024)
val surfaceContainerHighDark = Color(0xFF262B2E)
val surfaceContainerHighestDark = Color(0xFF313539)







